server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
        uri-encoding: utf-8
    port: 9000
    servlet:
      session:
        timeout: 30m

logging:
  level:
    root: INFO


spring:
  datasource:
    url: jdbc:mysql://172.16.102.156:3306/flowable?characterEncoding=UTF-8
    username: taxi
    password: zhcx123
    driver-class-name: com.mysql.jdbc.Driver
flowable:
  async-executor-activate: false
  database-schema-update: true
  process:
    definition-cache-limit: -1
